apiVersion: v1
kind: Secret
metadata:
  name: example-priv-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  project: default
  type: git
  url: https://gitlab.sikademo.com/example/3.git
  username: demo
  password: asdfasdf
